mis/src/main/java/lk/ac/pdn/eng/mis/entity/DefaultUserDetails.java
package lk.ac.pdn.eng.mis.entity;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;


public class DefaultUserDetails implements UserDetails{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private User user;
	
	
	public DefaultUserDetails(User user2) {
		this.user = user2;
	}
	
	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		List<GrantedAuthority> authList = new ArrayList<GrantedAuthority>(4);

		  if (user.getRole().compareTo("ADMIN") == 0) {
		    authList.add(new SimpleGrantedAuthority("ROLE_ADMIN"));
		  }if (user.getRole().compareTo("AR") == 0) {
			    authList.add(new SimpleGrantedAuthority("ROLE_AR"));
		  }if (user.getRole().compareTo("OFFICER") == 0) {
			    authList.add(new SimpleGrantedAuthority("ROLE_OFFICER"));
		  }
		  else{
		    authList.add(new SimpleGrantedAuthority("ROLE_STUDENT"));
		  }
		  return authList;
	}

	@Override
	public String getPassword() {
		return user.getPassword();
	}

	@Override
	public String getUsername() {
		return user.getUsername();
	}

	@Override
	public boolean isAccountNonExpired() {
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		return true;
	}

	@Override
	public boolean isEnabled() {
		return true;
	}
	
	public String getFullName() {
		return user.getFirstName()+ " "+ user.getLastName();
	}

	
}

mis/src/main/java/lk/ac/pdn/eng/mis/entity/PGStudent.java
package lk.ac.pdn.eng.mis.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

@Entity
@Table (name = "pgstudent")
public class PGStudent {
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int studentDataId;
	
	int year;
	String type; //degree level - PhD/M Phil/MSc/Diploma
	String department;
	String registrationNo;
	String title;
	String namewithinitials;
	String namedenotedbyInitials;
	String dateofRegistration;
	String id; //NIC
	
	@Lob 
	private byte[] photo;
	
	String contactNumber_s; //number(s)
	String emailAddress_s; //address(s)
	String postalAddress;
	String undergraduateDegree;
	String undergraduateClass;
	String undergraduateUniversity;
	String experienceinfield;
	String designation;
	String mScOrMScEng;
	String partTimeOrFullTime;
	String hDCMeetingNumber;
	String affiliatedLaboratory;
	String researchTitle;
	String supervisor_s; //supervisor(s)
	String examiner_s; //examiner(s)
	String stream;
	
	String programme;
	double courseFee;
	double libraryFee;
	double tuitionFee;
	double registrationFee;
	double firstYearPaymeent;
	double secondYearPaymeent;
	double thirdYearPaymeent;
	double fourthYearPaymeent;
	double programmeFee;
	double totalPaymentMade;
	
	
	public PGStudent() {
		super();
	}

	public PGStudent(int studentDataId, int year, String type, String department, String registrationNo, String title,
			String namewithinitials, String namedenotedbyInitials, String dateofRegistration, String id, byte[] photo,
			String contactNumber_s, String emailAddress_s, String postalAddress, String undergraduateDegree,
			String undergraduateClass, String undergraduateUniversity, String experienceinfield, String designation,
			String mScOrMScEng, String partTimeOrFullTime, String hDCMeetingNumber, String affiliatedLaboratory,
			String researchTitle, String supervisor_s, String examiner_s, String stream, int payment) {
		super();
		this.studentDataId = studentDataId;
		this.year = year;
		this.type = type;
		this.department = department;
		this.registrationNo = registrationNo;
		this.title = title;
		this.namewithinitials = namewithinitials;
		this.namedenotedbyInitials = namedenotedbyInitials;
		this.dateofRegistration = dateofRegistration;
		this.id = id;
		this.photo = photo;
		this.contactNumber_s = contactNumber_s;
		this.emailAddress_s = emailAddress_s;
		this.postalAddress = postalAddress;
		this.undergraduateDegree = undergraduateDegree;
		this.undergraduateClass = undergraduateClass;
		this.undergraduateUniversity = undergraduateUniversity;
		this.experienceinfield = experienceinfield;
		this.designation = designation;
		this.mScOrMScEng = mScOrMScEng;
		this.partTimeOrFullTime = partTimeOrFullTime;
		this.hDCMeetingNumber = hDCMeetingNumber;
		this.affiliatedLaboratory = affiliatedLaboratory;
		this.researchTitle = researchTitle;
		this.supervisor_s = supervisor_s;
		this.examiner_s = examiner_s;
		this.stream = stream;
		this.totalPaymentMade = payment;
	}

	public int getStudentDataId() {
		return studentDataId;
	}

	public void setStudentDataId(int studentDataId) {
		this.studentDataId = studentDataId;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getRegistrationNo() {
		return registrationNo;
	}

	public void setRegistrationNo(String registrationNo) {
		this.registrationNo = registrationNo;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getNamewithinitials() {
		return namewithinitials;
	}

	public void setNamewithinitials(String namewithinitials) {
		this.namewithinitials = namewithinitials;
	}

	public String getNamedenotedbyInitials() {
		return namedenotedbyInitials;
	}

	public void setNamedenotedbyInitials(String namedenotedbyInitials) {
		this.namedenotedbyInitials = namedenotedbyInitials;
	}

	public String getDateofRegistration() {
		return dateofRegistration;
	}

	public void setDateofRegistration(String dateofRegistration) {
		this.dateofRegistration = dateofRegistration;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public byte[] getPhoto() {
		return photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	public String getContactNumber_s() {
		return contactNumber_s;
	}

	public void setContactNumber_s(String contactNumber_s) {
		this.contactNumber_s = contactNumber_s;
	}

	public String getEmailAddress_s() {
		return emailAddress_s;
	}

	public void setEmailAddress_s(String emailAddress_s) {
		this.emailAddress_s = emailAddress_s;
	}

	public String getPostalAddress() {
		return postalAddress;
	}

	public void setPostalAddress(String postalAddress) {
		this.postalAddress = postalAddress;
	}

	public String getUndergraduateDegree() {
		return undergraduateDegree;
	}

	public void setUndergraduateDegree(String undergraduateDegree) {
		this.undergraduateDegree = undergraduateDegree;
	}

	public String getUndergraduateClass() {
		return undergraduateClass;
	}

	public void setUndergraduateClass(String undergraduateClass) {
		this.undergraduateClass = undergraduateClass;
	}

	public String getUndergraduateUniversity() {
		return undergraduateUniversity;
	}

	public void setUndergraduateUniversity(String undergraduateUniversity) {
		this.undergraduateUniversity = undergraduateUniversity;
	}

	public String getExperienceinfield() {
		return experienceinfield;
	}

	public void setExperienceinfield(String experienceinfield) {
		this.experienceinfield = experienceinfield;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getmScOrMScEng() {
		return mScOrMScEng;
	}

	public void setmScOrMScEng(String mScOrMScEng) {
		this.mScOrMScEng = mScOrMScEng;
	}

	public String getPartTimeOrFullTime() {
		return partTimeOrFullTime;
	}

	public void setPartTimeOrFullTime(String partTimeOrFullTime) {
		this.partTimeOrFullTime = partTimeOrFullTime;
	}

	public String gethDCMeetingNumber() {
		return hDCMeetingNumber;
	}

	public void sethDCMeetingNumber(String hDCMeetingNumber) {
		this.hDCMeetingNumber = hDCMeetingNumber;
	}

	public String getAffiliatedLaboratory() {
		return affiliatedLaboratory;
	}

	public void setAffiliatedLaboratory(String affiliatedLaboratory) {
		this.affiliatedLaboratory = affiliatedLaboratory;
	}

	public String getResearchTitle() {
		return researchTitle;
	}

	public void setResearchTitle(String researchTitle) {
		this.researchTitle = researchTitle;
	}

	public String getSupervisor_s() {
		return supervisor_s;
	}

	public void setSupervisor_s(String supervisor_s) {
		this.supervisor_s = supervisor_s;
	}

	public String getExaminer_s() {
		return examiner_s;
	}

	public void setExaminer_s(String examiner_s) {
		this.examiner_s = examiner_s;
	}

	public String getStream() {
		return stream;
	}

	public void setStream(String stream) {
		this.stream = stream;
	}

	
	public String getProgramme() {
		return programme;
	}

	public void setProgramme(String programme) {
		this.programme = programme;
	}

	public double getCourseFee() {
		return courseFee;
	}

	public void setCourseFee(double courseFee) {
		this.courseFee = courseFee;
	}

	public double getLibraryFee() {
		return libraryFee;
	}

	public void setLibraryFee(double libraryFee) {
		this.libraryFee = libraryFee;
	}

	public double getTuitionFee() {
		return tuitionFee;
	}

	public void setTuitionFee(double tuitionFee) {
		this.tuitionFee = tuitionFee;
	}

	public double getRegistrationFee() {
		return registrationFee;
	}

	public void setRegistrationFee(double registrationFee) {
		this.registrationFee = registrationFee;
	}

	public double getFirstYearPaymeent() {
		return firstYearPaymeent;
	}

	public void setFirstYearPaymeent(double firstYearPaymeent) {
		this.firstYearPaymeent = firstYearPaymeent;
	}

	public double getSecondYearPaymeent() {
		return secondYearPaymeent;
	}

	public void setSecondYearPaymeent(double secondYearPaymeent) {
		this.secondYearPaymeent = secondYearPaymeent;
	}

	public double getThirdYearPaymeent() {
		return thirdYearPaymeent;
	}

	public void setThirdYearPaymeent(double thirdYearPaymeent) {
		this.thirdYearPaymeent = thirdYearPaymeent;
	}

	public double getFourthYearPaymeent() {
		return fourthYearPaymeent;
	}

	public void setFourthYearPaymeent(double fourthYearPaymeent) {
		this.fourthYearPaymeent = fourthYearPaymeent;
	}

	public double getProgrammeFee() {
		return programmeFee;
	}

	public void setProgrammeFee(double programmeFee) {
		this.programmeFee = programmeFee;
	}

	public double getTotalPaymentMade() {
		return totalPaymentMade;
	}

	public void setTotalPaymentMade(double totalPaymentMade) {
		this.totalPaymentMade = totalPaymentMade;
	}

	public double getPayment() {
		return totalPaymentMade;
	}

	public void setPayment(double payment) {
		this.totalPaymentMade = payment;
	}	
}



/*

ATTRIBUTES

Year
Type
Department
Registration No
Title
Name with initials
Name denoted by Initials
Date of Registration
ID
photo
Contact Number(s)
E-mail Address(s)
Postal Address
Undergraduate Degree
Undergraduate Class
Undergraduate University
Expererience in field
Designation
M.Sc. or M.Sc.Eng.
Part Time/Full Time
HDC Meeting Number
Affiliated Laboratory
Research Title
Supervisor(s)
Examiner(s)
Stream
Payment

*/

mis/src/main/webapp/WEB-INF/views/admin/ArAccounts.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html ng-app="PageDetails">
<head>
<meta charset="ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MIS</title>
<link href="css/dashboard.css" rel="stylesheet">
<link href="css/admin.css" rel="stylesheet">
<link href="css/materialize.css" rel="stylesheet">
<link href="css/materialize.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
	rel="stylesheet">

<script type="text/javascript" src="js/angular.min.js"></script>
<script type="text/javascript" src="js/app.js"></script>
<script type="text/javascript" src="js/admin.js"></script>
	<script type="text/javascript" src="js/jquery-3.6.0.js"></script>
	<script type="text/javascript" src="js/materialize.min.js"></script>
<script type="text/javascript" src="js/lodash.min.js"></script>
	<script type="text/javascript">
	$(document).ready(function(){
	    $('.modal').modal();
	    $('#AddOfficer').on('click', function() {
		});
		$("#AddOfficer").modal({
			dismissible : false
		});
	  });
	$(document).ready(function(){
	    $('.sidenav').sidenav({
	    	draggable:true
	    });
	    $('.modal').modal();
	    $('.dropdown-trigger').dropdown();
	    $('#AddOfficer').on('click', function() {
		});
		$("#AddOfficer").modal({
			dismissible : false
		});
	  });
	$(document).ready(function(){
	    $('.tabs').tabs();
	    /* $('.tabs').tabs({
	        //swipeable : true,
	        responsiveThreshold : 1920
	     }); */
	    
	  });
	$('#left-side').on("click",".dashboard_link",function(e){ 
		  e.preventDefault(); // cancel click
		  var page = $(this).attr('href');   
		  $('body').fadeIn('slow', function(){
			 // $('body').fadeOut(300);
			  $('body').load(page);
			  window.history.pushState("Details", "Title", "/adminDashboard");
		  });
		});
	</script>

<body ng-controller="PageData">

	<div id="top">
	<ul id="dropdown1" class="dropdown-content">
		<li><a href="/logout">Logout</a></li>
	</ul>
	<nav class="navbar">
		<div class="nav-wrapper">
		<a href="#" data-target="slide-out" class="sidenav-trigger"><i
		class="material-icons">menu</i></a>
			<ul class="right">
				<!--  <li><a href="sass.html">Sass</a></li>
		      <li><a href="badges.html">Components</a></li> -->
				<!-- Dropdown Trigger -->
				<li><a class="dropdown-trigger" href="#!"
					data-target="dropdown1">${first_name} ${last_name}<i class="material-icons right">arrow_drop_down</i></a></li>
			</ul>
		</div>
	</nav>
	</div>

	<div id="left-side">
	<ul id="slide-out" class="sidenav sidenav-fixed z-depth-4">
		<li>

			<p class="MIS-logo">MIS</p>
		</li>
		<li><div class="divider"></div></li>
		<li class="nav-item active  "><a class="dashboard_link nav-link" href="/adminDashboard">
				<i class="material-icons">dashboard</i>
				<p>Dashboard</p>
		</a></li>
		<li class="nav-item "><a class="nav-link" href="/adminDashboard/myAccount">
				<i class="material-icons">person</i>
				<p>My Account</p>
		</a></li>
		<!-- <li class="nav-item "><a class="nav-link"
			href="./notifications.html"> <i class="material-icons">notifications</i>
				<p>Notifications</p>
		</a></li> -->
	</ul>
	</div>
	
	
	<div id="main_page" class="main_page">
	<!-- <h5> Student Accounts</h5>
	<div class="divider"></div> -->
	<div class="row">
	    <div class="col s12 m12 l4">
	        <div class="card cardHover">
                 <!-- <div class="card-image waves-effect waves-block waves-light">
                   image link 
                 </div> -->
                 <a href="#AddOfficer" class="black-text modal-trigger" ng-click="openAddArForm()">
                 <div class="card-content  waves-effect waves-block waves-light">
                   <span class="card-title activator text-darken-4">
                   ADD AR<i class="material-icons right" style="font-size: 55px;">person_add</i></span>
                 </div>
                 </a>
	    </div>
	    </div>
	  </div>
	  
	<h5> Ars</h5>
	<div class="divider"></div>
	<div class="row">
	    <div class="col s12 m12 l12">
	       <table class="responsive-table">
	       
	       <tr class="#bbdefb blue lighten-4">
	       <th>First Name</th>
	       <th>Last Name</th>
	       <th>Username</th>
	       <th>Address</th>
	       <th>Email</th>
	       <th>Mobile</th>
	       <th>Login Status</th>
	       </tr>
	       <tr ng-repeat="i in ars">
								<td>{{i.firstName}}</td>
								<td>{{i.lastName}}</td>
								<td>{{i.username}}</td>
								<td>{{i.address}}</td>
								<td>{{i.email}}</td>
								<td>{{i.mobileNumber}}</td>
								<td>{{i.loginStatus}}</td>
								<!-- <td><a
									class="waves-effect waves-light btn modal-trigger modal-close  light-blue darken-1"
									href="#UpdateCultivation" value="i.cultivationId"
									ng-click="updateClick(i.cultivationId,i.cultivationType,i.harvestAmount,i.location, i.availability,i.farmerId )"><i
										class="material-icons">edit</i></a></td>
								<td><a
									class="waves-effect waves-light btn modal-trigger modal-close  red darken-1"
									href="#DeleteCultivation" value="i.cultivationId"
									ng-click="deleteClick(i.cultivationId)"><i
										class="material-icons">delete</i></a></td>
								<td"></td> -->
								<td><div class="divider"></div></td>

			</tr>
	       </table>
	    </div>
	  </div>
	</div>
	
	<!-- Add Ars -->
	<div id="AddOfficer" class="modal">
				<div class="modal-content">
					<div class="raw">
						<div class="col s12 m12 l12">
							<div class="right-align">
								<button
									class="modal-close btn waves-effect waves-light pink darken-1 ">
									<i class="material-icons">close</i>
								</button>
							</div>
							<h5>ADD AR</h5>
						</div>
					</div>
					
					<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a class="active" href="#one">Add Ar</a></li>
					        <!-- <li class="tab col s3"><a href="#two">More Ars</a></li> -->
					      </ul>
					    </div>
					    <div id="one" class="col s12">
								<form>	
									<div class="row">
										<div class="input-field col s12 m12 l4">
											<input id="firstName" name="firstName" type="text"
												class="validate" ng-model="Ar_firstName"> <label
												for="firstName">First Name</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m12 l4">
											<input id="lastName" name="lastName" type="text"
												class="validate" ng-model="Ar_lastName"> <label
												for="lastName">Last Name</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m12 l4">
											<input id="username" name="username" type="text"
												class="username" ng-model="Ar_username"> <label
												for="username">Username</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m12 l4">
											<input id="password" name="password" type="text"
												class="password" ng-model="Ar_password"> <label
												for="password">Password</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m12 l4">
											<input id="nic" name="nic" type="text"
												class="validate" ng-model="Ar_nic"> <label
												for="nic">NIC No:</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m12 l4">
											<input id="address" name="address" type="text"
												class="validate" ng-model="Ar_address"> <label
												for="address">Address</label>
										</div>
									<!-- </div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m12 l4">
											<input id="email" name="email" type="email"
												class="validate" ng-model="Ar_email"> <label
												for="email">Email</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m12 l4">
											<input id="mobileNumber" name="mobileNumber" type="text"
												class="validate" ng-model="Ar_mobileNumber"> <label
												for="mobileNumber">Mobile No:</label>
										</div>
									<!-- </div> -->				
									<div class="modal-footer">
										<button class="btn waves-effect waves-light modal-close"
											type="submit" name="action" id="addAction"
											ng-click="addAr(Ar_firstName,Ar_lastName,Ar_username,Ar_password,Ar_nic,Ar_address,Ar_email,Ar_mobileNumber)">
											Add <i class="material-icons right">playlist_add</i>
										</button>
									</div>
									</div>
								</form>
						</div>
					    <!-- <div id="two" class="col s12">Upload Excel sheet here!</div> -->
					  </div>
				</div>
			</div>
</body>
</html>


<!-- <div style="text-align:center">
	<h1>Welcome to Spring Boot Admin DashBoard</h1>

	<h2>You are in Spring Boot Admin DashBoard Page</h2>
	<br><a href="/logout">logout</a>
	</div> -->

mis/src/main/webapp/WEB-INF/views/admin/MyAccount.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html ng-app="PageDetails">
<head>
<meta charset="ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MIS</title>
<link href="css/dashboard.css" rel="stylesheet">
<link href="css/admin.css" rel="stylesheet">
<link href="css/materialize.css" rel="stylesheet">
<link href="css/materialize.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
	rel="stylesheet">

<script type="text/javascript" src="js/angular.min.js"></script>
<script type="text/javascript" src="js/app.js"></script>
<script type="text/javascript" src="js/admin.js"></script>
	<script type="text/javascript" src="js/jquery-3.6.0.js"></script>
	<script type="text/javascript" src="js/materialize.min.js"></script>
<script type="text/javascript" src="js/lodash.min.js"></script>
	<script type="text/javascript">
	$(document).ready(function(){
	    $('.sidenav').sidenav({
	    	draggable:true
	    });
	    $('.modal').modal();
	    $('.dropdown-trigger').dropdown();
	  });
	$(document).ready(function(){
	    $('.tabs').tabs();
	    /* $('.tabs').tabs({
	        //swipeable : true,
	        responsiveThreshold : 1920
	     }); */
	    
	  });
	
	</script>

<body ng-controller="PageData" id="pageBody">

	<div id="top">
	<ul id="dropdown1" class="dropdown-content">
		<li><a href="/logout">Logout</a></li>
	</ul>
	<nav class="navbar">
		<div class="nav-wrapper">
		<a href="#" data-target="slide-out" class="sidenav-trigger"><i
		class="material-icons">menu</i></a>
			<ul class="right">
				<!--  <li><a href="sass.html">Sass</a></li>
		      <li><a href="badges.html">Components</a></li> -->
				<!-- Dropdown Trigger -->
				<li><a class="dropdown-trigger" href="#!"
					data-target="dropdown1">{{firstName}} {{lastName}}<i class="material-icons right">arrow_drop_down</i></a></li>
			</ul>
		</div>
	</nav>
	</div>

	<div id="left-side">
	<ul id="slide-out" class="sidenav sidenav-fixed z-depth-4">
		<li>

			<p class="MIS-logo">MIS</p>
		</li>
		<li><div class="divider"></div></li>
		<li class="nav-item active  "><a class="dashboard_link nav-link" href="/adminDashboard">
				<i class="material-icons">dashboard</i>
				<p>Dashboard</p>
		</a></li>
		<li class="nav-item "><a class="nav-link" href="/adminDashboard/myAccount">
				<i class="material-icons">person</i>
				<p>My Account</p>
		</a></li>
		<!-- <li class="nav-item "><a class="nav-link"
			href="./notifications.html"> <i class="material-icons">notifications</i>
				<p>Notifications</p>
		</a></li> -->
	</ul>
	</div>
	
	
	<div id="main_page" class="main_page">
	
	  
	<h5> MY ACCOUNT</h5>
	<div class="divider"></div>
	
	<div class="row">
					    <div class="col s12">
					      <ul class="tabs">
					        <li class="tab col s3"><a class="active" href="#one">SETTINGS</a></li>
					        <!-- <li class="tab col s3"><a href="#two">More Officers</a></li> -->
					      </ul>
					    </div>
					    <div id="one" class="col s12">
								<form >	
								
									<div class="row">
										<div class="input-field col s12 m6 l4">
											<input id="firstName" name="firstName" type="text"
												class="validate" ng-model="firstName" placeholder="{{firstName}}" value="{{firstName}}"> <label
												for="firstName">First Name</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m6 l4">
											<input id="lastName" name="lastName" type="text"
												class="validate" ng-model="lastName" placeholder="{{lastName}}" value="{{lastName}}"> <label
												for="lastName">Last Name</label>
										</div>
									<!-- </div>
									<%-- <div class="row"> -->
										<div class="input-field col s12 m6 l4">
											<input id="username" name="username" type="text"
												class="username" ng-model="username" placeholder="${username}"> <label
												for="username">Username</label>
										</div> --%>
									<!-- </div>
									<div class="row"> -->
										<!-- <div class="input-field col s12 m6 l4">
											<input id="password" name="password" type="text"
												class="password" ng-model="password"> <label
												for="password">Password</label>
										</div> -->
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m6 l4">
											<input id="nic" name="nic" type="text"
												class="validate" ng-model="nic" placeholder="{{nic}}" value="{{nic}}"> <label
												for="nic">NIC No:</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m6 l4">
											<input id="address" name="address" type="text"
												class="validate" ng-model="address" placeholder="{{address}}" value="{{address}}"> <label
												for="address">Address</label>
										</div>
									<!-- </div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m6 l4">
											<input id="email" name="email" type="email"
												class="validate" ng-model="email" placeholder="{{email}}" value="{{email}}"> <label
												for="email">Email</label>
										</div>
									<!-- </div>
									<div class="row"> -->
										<div class="input-field col s12 m6 l4">
											<input id="mobileNumber" name="mobileNumber" type="text"
												class="validate" ng-model="mobileNumber" placeholder="{{mobile}}" value="{{mobile}}"> <label
												for="mobileNumber">Mobile No:</label>
										</div>
									<!-- </div> -->				
									<div class="modal-footer">
										<button class="btn waves-effect waves-light modal-close"
											type="submit" name="action" id="updateAction"
											ng-click="updateAdmin(firstName,lastName,nic,address,email,mobileNumber)">
											Update <i class="material-icons right">playlist_add_check</i>
										</button> <b>{{updatedMsg}}</b>
									</div>
									</div>
								</form>
						</div>
					    <!-- <div id="two" class="col s12">Upload Excel sheet here!</div> -->
					  </div>
		</div>
</body>
</html>


<!-- <div style="text-align:center">
	<h1>Welcome to Spring Boot Admin DashBoard</h1>

	<h2>You are in Spring Boot Admin DashBoard Page</h2>
	<br><a href="/logout">logout</a>
	</div> -->